### ISSUE TITLE
drag/drop file upload doesn't work for non-mac

### ISSUE THREAD

**Issue by sdwoodbury** [Satellite-im/WarpGUI#510]
I noticed this while reviewing this [PR](https://github.com/Satellite-im/Uplink/pull/488) . `main/files/upload/mod.rs` expects that when the `ondragover` event is triggered, `DROPPED_FILE.files_local_path` will be non-empty. The code panics when dropping a file:

```
RUST_LOG=debug target/debug/uplink
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', src/components/main/files/upload/mod.rs:71:64
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }', /home/fu/.cargo/registry/src/github.com-1ecc6299db9ec823/dioxus-desktop-0.2.3/src/lib.rs:143:87
Segmentation fault (core dumped)
```

Copying the drop handler from macos stops the panic but as described in the linked PR, the drag/drop still doesn't work. 

`src/main.rs`
![image](https://user-images.githubusercontent.com/8636602/205326649-0b3b7b43-a913-4f4b-b59a-c96435e7177f.png)

debug log after adding the drop handler:

```
tail -f warp-gui.log.2022-12-02-14 | grep uplink
2022-12-02T14:52:41.962056Z DEBUG uplink::components::reusable::sidebar: rendering reusable Sidebar    
2022-12-02T14:52:41.962462Z DEBUG uplink::components::reusable::nav: rendering reusable Nav    
2022-12-02T14:52:41.963976Z DEBUG uplink::components::reusable::toolbar: rendering reusable Toolbar    
2022-12-02T14:52:41.964276Z DEBUG uplink::components::reusable::nav: rendering reusable Nav    
2022-12-02T14:52:41.968237Z DEBUG uplink::components::main::files::browser: updating files list    
2022-12-02T14:52:46.277768Z DEBUG uplink::components::reusable::toolbar: rendering reusable Toolbar    
2022-12-02T14:52:49.796832Z  INFO uplink::components::main::files::upload: File on dropzone    
2022-12-02T14:52:49.897721Z  INFO uplink::components::main::files::upload: File on dropzone    
2022-12-02T14:52:49.999205Z  INFO uplink::components::main::files::upload: File on dropzone    
2022-12-02T14:52:50.099897Z  INFO uplink::components::main::files::upload: File on dropzone    
2022-12-02T14:52:50.201490Z  INFO uplink::components::main::files::upload: File on dropzone    
2022-12-02T14:52:50.303106Z  INFO uplink::components::main::files::upload: File on dropzone    
2022-12-02T14:52:50.403736Z  INFO uplink::components::main::files::upload: File on dropzone    
2022-12-02T14:52:50.505111Z  INFO uplink::components::main::files::upload: File on dropzone    
2022-12-02T14:52:50.605683Z  INFO uplink::components::main::files::upload: File on dropzone    
2022-12-02T14:52:50.707286Z  INFO uplink::components::main::files::upload: File on dropzone    
2022-12-02T14:52:50.807868Z  INFO uplink::components::main::files::upload: File on dropzone    
2022-12-02T14:52:50.909555Z  INFO uplink::components::main::files::upload: File on dropzone    
2022-12-02T14:52:51.011141Z  INFO uplink::components::main::files::upload: File on dropzone    
2022-12-02T14:52:51.111705Z  INFO uplink::components::main::files::upload: File on dropzone    
2022-12-02T14:52:51.213073Z  INFO uplink::components::main::files::upload: File on dropzone    
2022-12-02T14:52:51.314007Z  INFO uplink::components::main::files::upload: File on dropzone    
2022-12-02T14:52:51.438893Z  INFO uplink::components::main::files::upload: File not able to upload    
2022-12-02T14:52:53.955332Z  INFO uplink::components::main::files::upload: File not able to upload    
2022-12-02T14:53:08.727457Z  INFO uplink::components::main::files::upload: File on dropzone    
2022-12-02T14:53:08.828595Z  INFO uplink::components::main::files::upload: File on dropzone    
2022-12-02T14:53:08.930249Z  INFO uplink::components::main::files::upload: File on dropzone    
2022-12-02T14:53:09.030949Z  INFO uplink::components::main::files::upload: File on dropzone    
2022-12-02T14:53:09.132490Z  INFO uplink::components::main::files::upload: File on dropzone    
2022-12-02T14:53:09.234179Z  INFO uplink::components::main::files::upload: File on dropzone    
2022-12-02T14:53:09.334792Z  INFO uplink::components::main::files::upload: File on dropzone    
2022-12-02T14:53:09.436368Z  INFO uplink::components::main::files::upload: File on dropzone    
2022-12-02T14:53:09.671258Z  INFO uplink::components::main::files::upload: File not able to upload    
2022-12-02T14:53:10.771846Z  INFO uplink::components::main::files::upload: File not able to upload 
```

**Comment by sdwoodbury** [comment]
related to https://github.com/Satellite-im/Uplink/issues/378

**Comment by dariusc93** [comment]
I may take a closer look at this very soon if nobody else does

**Comment by sdwoodbury** [comment]
i just checked - still not working on Linux
